apiVersion: v1
kind: Service
metadata:
  name: required-annotations-allowed-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: ann
---
kind: Namespace
apiVersion: v1
metadata:
  name: required-annotations-allowed-service-ns
  labels:
     app: ann
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: required-annotations-allowed-deployment
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ann
  template:
    metadata:
      labels:
        app: ann
    spec:
      containers:
       - name: test
         image: nginx