kind: Service
apiVersion: v1
metadata:
  name: mutating-webhook-demo
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mutating-admission-webhook
  ports:
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mutating-webhook-server
  name: mutating-admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutating-admission-webhook
  template:
    metadata:
      labels:
        app: mutating-admission-webhook
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
        - name: certs
          secret:
           secretName: mutating-webhook-tls
      containers:
        - name: vaws
          image: lerndevops/samples:mutating-webhook-server
          #command: ["/bin/bash", "-c", "sleep 6000"]
          ports:
           - name: https
             containerPort: 443
          volumeMounts:
           - name: certs
             mountPath: /tmp/ssl