apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
  namespace: default
webhooks:
  - name: mutating-webhook-demo.default.svc
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    clientConfig:
      service:
        name: mutating-webhook-demo
        namespace: default
        path: /mutate/deployments
      caBundle: <PLACE-YOUR-WEBHOOK-SERVER_CA-HERE><MUST BE base64 encoded data>
    rules:
      - apiGroups:
          - "apps"
        resources:
          - "deployments"
        apiVersions:
          - "*"
        operations:
          - CREATE


