apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutation-test-deployment
  annotations:
    author: naresh
  labels:
    app: mutation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutation
  template:
    metadata:
      labels:
        app: mutation
    spec:
      containers:
      - image: nginx
        name: nginx