apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
  namespace: default
webhooks:
  - name: validating-webhook-demo.default.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: validating-webhook-demo
        namespace: default
        path: /validate
      caBundle: <PLACE-YOUR-WEBHOOK-SERVER_CA-HERE><MUST BE base64 encoded data>
    rules:
      - apiGroups: 
          - "apps"
          - ""
        resources:
          - "deployments"
          - "pods"
        apiVersions:
          - "*"
        operations:
          - CREATE